# ==========================================
# WOMBO COMBO - iOS Build para Desarrollador Independiente
# VERSIÓN CON FIRMA AUTOMÁTICA Y SUBIDA A TESTFLIGHT
# ==========================================

workflows:
  ios-build-and-upload:
    name: "Wombo Combo - Build & Upload to TestFlight"
    description: "Build, firma automática y subida a TestFlight"
    instance_type: mac_mini_m2

    # --- INTEGRACIÓN CON APP STORE CONNECT (NUEVO) ---
    integrations:
      app_store_connect: Codemagic CI  # El nombre que le diste a la integración en la web de Codemagic

    environment:
      flutter: "stable"
      xcode: "latest"
      cocoapods: "default"

      # --- CONFIGURACIÓN DE FIRMA AUTOMÁTICA (NUEVO) ---
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.javiersanchez.womboCombo

      vars:
        APPLE_ID: "javiersanchezmartinez2006@gmail.com"
        APP_IDENTIFIER: "com.javiersanchez.womboCombo"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.javiersanchez.womboCombo"
        APP_NAME: "Wombo Combo"

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/Library/Caches/CocoaPods
        - ios/Pods
        - $HOME/Library/Developer/Xcode/DerivedData

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
      cancel_previous_builds: false

    scripts:
      # ---------- STAGE 1: SETUP ----------
      - name: "Stage 1: Setup"
        script: |
          # ... (tu script existente, no necesita cambios) ...
          echo "=========================================="
          echo "🚀 INICIANDO BUILD - WOMBO COMBO"
          echo "=========================================="
          echo "Fecha: $(date)"
          echo ""
          flutter config --no-analytics
          echo "📱 INFORMACIÓN DEL SISTEMA:"
          echo "--------------------------"
          flutter --version
          echo ""
          xcodebuild -version
          echo ""
          echo "Bundle ID: $APP_IDENTIFIER"
          echo "Apple ID: $APPLE_ID"
          echo ""

      # ---------- STAGE 2: CLEAN ----------
      - name: "Stage 2: Clean"
        script: |
          # ... (tu script existente) ...
          echo "=========================================="
          echo "🧹 LIMPIANDO PROYECTO"
          echo "=========================================="
          rm -rf android 2>/dev/null || true
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Runner.xcworkspace 2>/dev/null || true
          rm -rf ~/Library/Developer/Xcode/DerivedData/* 2>/dev/null || true
          rm -rf ~/.pub-cache 2>/dev/null || true
          echo "✅ Proyecto limpiado completamente"
          echo ""

      # ---------- STAGE 3: DEPENDENCIAS ----------
      - name: "Stage 3: Dependencies"
        script: |
          # ... (tu script existente) ...
          echo "=========================================="
          echo "📦 INSTALANDO DEPENDENCIAS"
          echo "=========================================="
          flutter pub get
          flutter pub run flutter_launcher_icons:main
          echo "✅ Dependencias instaladas"
          echo ""

      # ---------- STAGE 4: iOS SETUP ----------
      - name: "Stage 4: iOS Setup"
        script: |
          # ... (tu script existente, NO necesitas modificar el Bundle ID manualmente porque ya se hizo en el código, pero no está de más) ...
          echo "=========================================="
          echo "🍏 CONFIGURANDO PROYECTO iOS"
          echo "=========================================="
          if [ ! -d "ios" ]; then
            echo "Creando proyecto iOS..."
            flutter create --platforms=ios --org com.javiersanchez --project-name wombocombo .
            echo "✅ Proyecto iOS creado"
          else
            echo "✅ Proyecto iOS ya existe"
          fi
          # Asegurar Bundle ID en Info.plist
          cd ios
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $APP_IDENTIFIER" Runner/Info.plist 2>/dev/null || echo "Bundle ID ya configurado"
          cd ..
          echo "Instalando CocoaPods..."
          cd ios
          pod repo update
          pod install --verbose
          cd ..
          echo "✅ iOS configurado correctamente"
          echo ""

      # ---------- STAGE 5: APLICAR PERFILES DE FIRMA (NUEVO) ----------
      - name: "Stage 5: Apply Code Signing Profiles"
        script: |
          echo "=========================================="
          echo "🔑 APLICANDO PERFILES DE FIRMA"
          echo "=========================================="
          # Este comando usa la API de App Store Connect para obtener los perfiles correctos
          xcode-project use-profiles
          echo "✅ Perfiles de firma aplicados"
          echo ""

      # ---------- STAGE 6: CONSTRUIR IPA (MODIFICADO) ----------
      - name: "Stage 6: Build IPA"
        script: |
          echo "=========================================="
          echo "🔨 CONSTRUYENDO IPA (FIRMADO)"
          echo "=========================================="
          # Construir el IPA para la App Store. La firma se hará automáticamente.
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
          echo "✅ Build de IPA completado"
          echo ""

      # ---------- STAGE 7: PREPARAR ARTEFACTOS (OPCIONAL) ----------
      - name: "Stage 7: Prepare artifacts"
        script: |
          echo "=========================================="
          echo "📦 PREPARANDO ARTEFACTOS"
          echo "=========================================="
          mkdir -p app_store_package
          # Copiar el IPA firmado generado por Flutter
          if [ -f "build/ios/ipa/WomboCombo.ipa" ]; then
            cp "build/ios/ipa/WomboCombo.ipa" "app_store_package/"
            echo "✅ IPA firmado copiado"
          elif [ -f "build/ios/ipa/Runner.ipa" ]; then
            cp "build/ios/ipa/Runner.ipa" "app_store_package/WomboCombo.ipa"
            echo "✅ IPA firmado copiado como WomboCombo.ipa"
          else
            echo "⚠️  IPA no encontrado en la ruta esperada."
            find build -name "*.ipa" -ls
          fi
          ls -la app_store_package/
          echo ""

    artifacts:
      - app_store_package/*.ipa
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      # --- PUBLICACIÓN AUTOMÁTICA A TESTFLIGHT (NUEVO) ---
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY      # Se inyecta automáticamente por la integración
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER    # Se inyecta automáticamente
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID      # Se inyecta automáticamente
        submit_to_testflight: true                    # Subir automáticamente a TestFlight
        # beta_groups: ["Tus Testers"] # Opcional: nombre del grupo en TestFlight

      email:
        recipients:
          - javiersanchezmartinez2006@gmail.com
        notify:
          success: true
          failure: true
